config/routes.rb
Rails.application.routes.draw do
  root :to => "secret#index"
  resources :secrets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  generate_public_uid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/secret_controller.rb
class SecretController < ApplicationController
  def index
    @secret = Secret.new
    @secrets = Secret.all
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def create
    @secret = Secret.new(secret_params)
    @secret.save
    redirect_to root_path
  end

  def show
    @secret = Secret.find_by(public_uid: params[:id])
    if @secret
      @secret.destroy
    else
      redirect_to root_path
    end

  end

  private
    def secret_params
      params.require(:secret).permit(:message)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secret_helper.rb
module SecretHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/secret/index.html.erb
<%= form_for @secret, url: secrets_path do |f| %>
  <%= f.text_area :message, placeholder: "Put your secret message here!" %>
  <%= f.submit "Post", class: 'btn btn-primary' %>
<% end %>

<% @secrets.each do |p| %>
  <div>URL: <%= request.base_url %>/secrets/<%= p.public_uid %></div>
  </br></br>
<% end %>

app/views/secrets/show.html.erb
<%= @secret.message %>
<%= link_to "Home", root_path %>